### ISSUE TITLE
max_open_trades

### ISSUE THREAD

**Issue by Dannex** [jilv220/BB_RPB_TSL#2]
Can you please tell me if you are still using "max_open_trades": 5 ?
In your backtests results v103 and v104 I see "Max open trades = 86, 97, etc..." how is it possbile if you are using "max_open_trades": 5  in your conifg.json?

Thanks

**Comment by jilv220** [comment]
The backtest uses unlimited max_open_trades to fully test the strategy. If I use 5 instead, maybe there would be some bad trades avoided. (Since all slots are taken)  

In my dry run, I still used "max_open_trades": 5

**Comment by Dannex** [comment]
I don't know how can you run in dry_run on kucoin...I get "429 Too Many Requests {"code":"429000","msg":"Too Many Requests"}" error and I don't think the region is the issue.

I am trying to adjust your strategy which looks great and powerfull to Binance but I can't get even close to kucoin results...My profit in backtesting for a month it's around 2% and can't see why

**Comment by jilv220** [comment]
Do u re-hyperopt yourself ? The strategy is hyperopted for kucoin.

**Comment by Dannex** [comment]
Yep, I've hyperopt it with ShortTradeDurHyperOptLoss, but did not see any improvements. And after hyperopt it's adding stop_loss and more condtioins on roi....maybe I'm doing something wrong

**Comment by jilv220** [comment]
Umm.. Maybe I will try to make a binance version myself if I have time.
