### ISSUE TITLE
differences

### ISSUE THREAD

**Issue by liquidmind313** [jilv220/BB_RPB_TSL#5]
Huge Thanks for your work!
I just wanted to ask about differences in:
BB_RPB_TSL, 
what is _RNG and  _TBS  ?

**Comment by jilv220** [comment]
RNG is a previous version of BB_RPB_TSL with sell signals modded by RNGsus. 
For TBS, I have no idea which modded version is that.

**Comment by liquidmind313** [comment]
[BB_RPB_TSL_RNG_TBS.py.zip](https://github.com/jilv220/BB_RPB_TSL/files/7580594/BB_RPB_TSL_RNG_TBS.py.zip)

**Comment by Smidelis** [comment]
TBS means trailing buy strat. This has come up in the FT discord. Seems someone has added trailing buy to BB_RPB_RSL by RNGsus

**Comment by jilv220** [comment]
Will probably also add TrailbuyStra2 to BB_RPB_TSL.
